# -*- coding: utf-8 -*-

__all__ = (
    'CONTRACT_ENDPOINT_REGISTRY',
    'CONTRACT_HUMAN_STANDARD_TOKEN',
    'CONTRACT_TOKEN_NETWORK_REGISTRY',
    'CONTRACT_TOKEN_NETWORK',
    'CONTRACT_SECRET_REGISTRY_NAME',

    'EVENT_TOKEN_NETWORK_CREATED',

    'EVENT_CHANNEL_OPENED',
    'EVENT_CHANNEL_DEPOSIT',
    'EVENT_CHANNEL_WITHDRAW',
    'EVENT_CHANNEL_BALANCE_PROOF_UPDATED',
    'EVENT_CHANNEL_CLOSED',
    'EVENT_CHANNEL_SETTLED',
    'EVENT_CHANNEL_UNLOCK',

    'EVENT_SECRET_REVEALED',
)

CONTRACT_ENDPOINT_REGISTRY = 'EndpointRegistry'
CONTRACT_HUMAN_STANDARD_TOKEN = 'HumanStandardToken'
CONTRACT_TOKEN_NETWORK_REGISTRY = 'TokenNetworkRegistry'
CONTRACT_TOKEN_NETWORK = 'TokenNetwork'
CONTRACT_SECRET_REGISTRY_NAME = 'SecretRegistry'

# TokenNetworkRegistry
EVENT_TOKEN_NETWORK_CREATED = 'TokenNetworkCreated'

# TokenNetwork
EVENT_CHANNEL_OPENED = 'ChannelOpened'
EVENT_CHANNEL_DEPOSIT = 'ChannelNewDeposit'
EVENT_CHANNEL_WITHDRAW = 'ChannelWithdraw'
EVENT_CHANNEL_BALANCE_PROOF_UPDATED = 'NonClosingBalanceProofUpdated'
EVENT_CHANNEL_CLOSED = 'ChannelClosed'
EVENT_CHANNEL_SETTLED = 'ChannelSettled'
EVENT_CHANNEL_UNLOCK = 'ChannelUnlocked'

# SecretRegistry
EVENT_SECRET_REVEALED = 'SecretRevealed'
