C_SECRET_REGISTRY = 'SecretRegistry'
C_TOKEN_NETWORK_REGISTRY = 'TokenNetworkRegistry'
C_TOKEN_NETWORK = 'TokenNetwork'
C_HUMAN_STANDARD_TOKEN = 'HumanStandardToken'
C_CUSTOM_TOKEN = 'CustomToken'

E_CHANNEL_OPENED = 'ChannelOpened'
E_CHANNEL_NEW_DEPOSIT = 'ChannelNewDeposit'
E_CHANNEL_CLOSED = 'ChannelClosed'
E_CHANNEL_UNLOCKED = 'ChannelUnlocked'
E_TRANSFER_UPDATED = 'TransferUpdated'
E_CHANNEL_SETTLED = 'ChannelSettled'
E_TOKEN_NETWORK_CREATED = 'TokenNetworkCreated'
E_SECRET_REVEALED = 'SecretRevealed'
